<a href="https://colab.research.google.com/github/mohanrajmit/MLDS_HACK/blob/master/MLDS_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy

Using TensorFlow backend.


In [2]:
!git clone https://github.com/mohanrajmit/MLDS_HACK.git

Cloning into 'MLDS_HACK'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 14 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (14/14), done.


In [3]:
from pandas import read_csv
filename = '/content/MLDS_HACK/Data_Train.csv'
#names = ['F_1', 'F_3', 'F_5', 'F_7', 'F_6', 'F_8','Labels']
train_data = read_csv(filename)
print(train_data.shape)

(34800, 7)


In [4]:
train_data.head()

F_1  F_3   F_5   F_7   F_6  F_8  Labels
0  0.0  2.0   0.0  39.0  39.0  2.0     1.0
1  3.0  0.0 -16.0  39.0  39.0  0.0     5.0
2  0.0  0.0  16.0  39.0  39.0  0.0     1.0
3  1.0  0.0   4.0  37.0  37.0  0.0     1.0
4  0.0  0.0  17.0  67.0  67.0  0.0     1.0

In [5]:
class_counts = train_data.groupby('Labels').size()
print(class_counts)

Labels
1.0    27286
2.0       30
3.0      106
4.0     5398
5.0     1966
6.0        5
7.0        9
dtype: int64


In [0]:
import numpy as np
train_data = np.asarray(train_data)

In [0]:
#train_data1=trao
train_data1 = train_data[:,0:6]
train_labels = train_data[:,6]

In [0]:
train_labels =train_labels.astype(np.int32)

In [9]:
print(train_data1[0])
print(train_labels[0])

[ 0.  2.  0. 39. 39.  2.]
1


In [10]:
test_filename = '/content/MLDS_HACK/Data_Test.csv'
#test_names = ['F_1', 'F_3', 'F_5', 'F_7', 'F_6', 'F_8']
test_data = read_csv(test_filename)
print(test_data.shape)

(8700, 6)


In [11]:
test_data.head()

F_1  F_3   F_5   F_7   F_6  F_8
0  2.0 -5.0   7.0  35.0  35.0 -5.0
1  0.0  0.0 -30.0  78.0  78.0  0.0
2  0.0  6.0  23.0  42.0  42.0  6.0
3 -1.0 -5.0   0.0  28.0  28.0 -5.0
4 -5.0  1.0   1.0  28.0  28.0  1.0

In [12]:
print(train_labels.shape)

(34800,)


In [13]:
print(train_labels[0])

1


In [0]:
train_labels_final=[]
for row in train_labels:
  train_labels_final.append(row-1)

In [0]:
from keras.utils import np_utils
number_of_classes = 7

Y_train = np_utils.to_categorical(train_labels_final, number_of_classes,dtype=np.float32)

In [16]:
print(Y_train[0])

[1. 0. 0. 0. 0. 0. 0.]


In [0]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
train_normalized = scaler.fit_transform(train_data1)

In [32]:
print(train_normalized[0:5,:])

[[0.5067802  0.50727249 0.51280246 0.62921348 0.62921348 0.50727249]
 [0.50709555 0.50701506 0.51220958 0.62921348 0.62921348 0.50701506]
 [0.5067802  0.50701506 0.51339534 0.62921348 0.62921348 0.50701506]
 [0.50688531 0.50701506 0.51295068 0.62600321 0.62600321 0.50701506]
 [0.5067802  0.50701506 0.51343239 0.6741573  0.6741573  0.50701506]]


In [33]:
#from sklearn.preprocessing import Normalizer
scaler1 = MinMaxScaler(feature_range=(0, 1))
test_normalized = scaler1.fit_transform(test_data)
print(test_normalized[0:5,:])

[[0.47160883 0.2826087  0.31789292 0.80331263 0.80331263 0.2826087 ]
 [0.47138351 0.29249012 0.31390714 0.89233954 0.89233954 0.29249012]
 [0.47138351 0.30434783 0.3196165  0.81780538 0.81780538 0.30434783]
 [0.47127084 0.2826087  0.31713886 0.78881988 0.78881988 0.2826087 ]
 [0.47082019 0.2944664  0.31724658 0.78881988 0.78881988 0.2944664 ]]


#pima indian dataset


In [34]:
# create model
model = Sequential()
model.add(Dense(12, input_dim=6, init='uniform', activation='relu'))

model.add(Dense(8, init='uniform', activation='relu'))
model.add(Dense(8, init='uniform', activation='relu'))
model.add(Dense(7, init='uniform', activation='softmax'))
# Compile model

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(12, input_dim=6, activation="relu", kernel_initializer="uniform")`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, activation="relu", kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, activation="relu", kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, activation="softmax", kernel_initializer="uniform")`
  """


In [0]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [36]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 12)                84        
_________________________________________________________________
dense_6 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_7 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_8 (Dense)              (None, 7)                 63        
Total params: 323
Trainable params: 323
Non-trainable params: 0
_________________________________________________________________


In [37]:
# Fit the model
model.fit(train_normalized, Y_train, nb_epoch=200, batch_size=None)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/200
34800/34800 [==============================] - 4s 117us/step - loss: 0.8074 - acc: 0.7834
Epoch 2/200
34800/34800 [==============================] - 4s 111us/step - loss: 0.6701 - acc: 0.7841
Epoch 3/200
34800/34800 [==============================] - 4s 107us/step - loss: 0.6703 - acc: 0.7841
Epoch 4/200
34800/34800 [==============================] - 4s 113us/step - loss: 0.6703 - acc: 0.7841
Epoch 5/200
34800/34800 [==============================] - 4s 113us/step - loss: 0.6701 - acc: 0.7841
Epoch 6/200
34800/34800 [==============================] - 4s 112us/step - loss: 0.6697 - acc: 0.7841
Epoch 7/200
34800/34800 [==============================] - 4s 109us/step - loss: 0.6705 - acc: 0.7841
Epoch 8/200
34800/34800 [==============================] - 4s 109us/step - loss: 0.6700 - acc: 0.7841
Epoch 9/200
34800/34800 [==============================] - 4s 111us/step - loss: 0.6702 - acc: 0.7841
Epoch 10/200
34800/34800 [==============================] - 4s 110us/step - loss: 

In [0]:
predictions = model.predict_proba(test_normalized)
predictions = list(predictions)

In [0]:
predictions =np.asarray(predictions)

In [26]:
print(predictions.shape)

(8700, 7)


In [0]:
names = ['THROTTLE HIGH','RAD','P1 BYPASSED','FPV OPENED','PRESSURE VALVE OPEN','CLOSED FPV','PRESSURE VALVE CLOSED']
numpy.savetxt("res1.csv", predictions,delimiter=",",header='THROTTLE HIGH,RAD,P1 BYPASSED,FPV OPENED,PRESSURE VALVE OPEN,CLOSED FPV,PRESSURE VALVE CLOSED')